# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

# Please consult the lectures
Vectors are 1-dimensional arrays, whereas matrices are 2-dimensional arrays.

**2. How to import `NumPy` library?** 

In [244]:
# To avoid overwriting the output, please code here 
import numpy as np


**3. Convert the given Python list into NumPy array and check its data type**

In [245]:
list_1 = [1,2,3,4,5]

In [246]:
# To avoid overwriting the output, please code here 
list_1 = [1, 2, 3, 4, 5]
array_1 = np.array(list_1)
print(array_1, type(array_1))


[1 2 3 4 5] <class 'numpy.ndarray'>


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [247]:
# To avoid overwriting the output, please code here 
array_2 = np.arange(6)
print(array_2)


[0 1 2 3 4 5]


**5. Generate an `array of "5" zeros` **

In [248]:
# To avoid overwriting the output, please code here 
array_3 = np.zeros(5)
print(array_3)


[0. 0. 0. 0. 0.]


**6. Generate the following `matrix`.**

In [249]:
# To avoid overwriting the output, please code here 
matrix_1 = np.zeros((3, 4))
print(matrix_1)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [250]:
# To avoid overwriting the output, please code here 
array_4 = np.ones(5)
print(array_4)


[1. 1. 1. 1. 1.]


**8. Generate an array of "5" tens.**

In [251]:
# To avoid overwriting the output, please code here 
array_5 = np.full(5, 10)
print(array_5)


[10 10 10 10 10]


**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [252]:
# To avoid overwriting the output, please code here 
even_numbers = np.arange(52, 100, 2)
print(even_numbers)


[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [253]:
# To avoid overwriting the output, please code here 
linear_space = np.linspace(0, 1, 10)
step_size = linear_space[1] - linear_space[0]
print(linear_space, step_size)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] 0.1111111111111111


**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [254]:
# To avoid overwriting the output, please code here 
vector = np.arange(25)
matrix_2 = vector.reshape(5, 5)
print(matrix_2)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**12. Please generate the following matrix.**

In [255]:
# To avoid overwriting the output, please code here
matrix_3 = np.arange(0.1, 2.6, 0.1).reshape(5, 5)
print(matrix_3)
 

[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]
 [2.1 2.2 2.3 2.4 2.5]]


**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [256]:
# To avoid overwriting the output, please code here 
matrix_4 = np.linspace(0, 24, 25).reshape(5, 5)
print(matrix_4)


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


**14. What is the main difference between `linspace()` and `arange()`?**

.arange() specifies the step size.
.linspace() specifies the number of points.

**15. How to generate a single random integer number using NumPy built-in function?**

In [258]:
# To avoid overwriting the output, please code here 
random_int = np.random.randint(1, 100)
print(random_int)


51


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [259]:
# To avoid overwriting the output, please code here 
matrix_5 = np.random.rand(7, 5)
print(matrix_5)


[[0.14282844 0.27149496 0.34926661 0.63777953 0.10216491]
 [0.53576662 0.58455051 0.78907423 0.68332207 0.01575971]
 [0.72371105 0.94193481 0.3678813  0.03574755 0.7859362 ]
 [0.60279124 0.85911197 0.4078375  0.06973572 0.15232035]
 [0.24069029 0.27457054 0.29060679 0.8509188  0.16319083]
 [0.57278149 0.23982798 0.42439855 0.44639023 0.79554108]
 [0.73378697 0.62712054 0.28384455 0.10253738 0.49083329]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [260]:
# To avoid overwriting the output, please code here 
identity_matrix = np.eye(5) * 5
print(identity_matrix)



[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 